// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4A5xW56W-0TNEeRdKiZ5VqNPyx2E4UU0',
    appId: '1:324997730538:web:1cc6bb5f7183e3af1f0793',
    messagingSenderId: '324997730538',
    projectId: 'my-flutter-963fe',
    authDomain: 'my-flutter-963fe.firebaseapp.com',
    storageBucket: 'my-flutter-963fe.appspot.com',
    measurementId: 'G-C42ECRPKE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwOT9nnlClK3VTrLICP0CPZ8IEIUMsbc',
    appId: '1:324997730538:android:b3f41ea9b9ab95571f0793',
    messagingSenderId: '324997730538',
    projectId: 'my-flutter-963fe',
    storageBucket: 'my-flutter-963fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXzR-khd9q3HU6m3n18_0JAYBsw23Amm4',
    appId: '1:324997730538:ios:34f5164a35a7ae841f0793',
    messagingSenderId: '324997730538',
    projectId: 'my-flutter-963fe',
    storageBucket: 'my-flutter-963fe.appspot.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXzR-khd9q3HU6m3n18_0JAYBsw23Amm4',
    appId: '1:324997730538:ios:b899557334ec6a271f0793',
    messagingSenderId: '324997730538',
    projectId: 'my-flutter-963fe',
    storageBucket: 'my-flutter-963fe.appspot.com',
    iosBundleId: 'com.example.firstFlutterApp.RunnerTests',
  );
}
